version: '3'
services:
  elixir:
    build: .
    ports:
     - "5000:5000"
    volumes:
      - .:/mmo
    stdin_open: true
    tty: true
  client:
    build:
      context: .
      dockerfile: Dockerfile-client
    stdin_open: true
    tty: true
  redis:
    image: "redis:alpine"